name: Generate

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-20.04  # Required for Python 3.6.
    name: Generate
    strategy:
      matrix:
        python: [3.5, 3.6]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: pmaupin/pdfrw
      - uses: actions/checkout@v3
        with:
          repository: pmaupin/static_pdfs
          path: tests/static_pdfs
      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: prepare pip
        run:
          python -m pip install --upgrade pip wheel
      - name: install package
        run:
          python -m pip install .
      # Uses `reportlab` available during last actual release.
      - name: install Python deps
        run:
          python -m pip install --upgrade reportlab==3.4.0 pycrypto pytest
      - name: run tests
        run: |
          cd tests
          PYTHONPATH=. pytest --verbose
      - name: display result directory
        if: always()
        run:
          tree tests/tmp_results/
      - name: upload
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: python${{ matrix.python }}_results
          path: |
            tests/tmp_results/*
